// number 增加
const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;
// number 减少
const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM ';
type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;


export {
    INCREMENT_ENTHUSIASM,
    DECREMENT_ENTHUSIASM,
}